name: Build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pip
          pip install pipenv
          pipenv install --system

      - name: Build Markdown
        run: |
          python -m apa.cli build markdown

      - uses: stefanzweifel/git-auto-commit-action@v4
